runtime: nodejs14

handlers:
  - url: /images
    static_dir: www/images

  - url: /css
    static_dir: www/css

  - url: /js
    static_dir: www/js

  - url: /(.*\.(gif|png|jpg|css|js|html|json))
    static_files: www/\1
    upload: www/(.*\.(gif|png|jpg|css|js|html|json))

  - url: /.*
    script: auto
